# $_source=https://github.com/1Mill/lambda-docker/blob/main/nodejs/v18/2023-09-13/dockerfile
# syntax=docker/dockerfile:1

# * https://gallery.ecr.aws/lambda/nodejs
FROM public.ecr.aws/lambda/nodejs:18

WORKDIR $LAMBDA_TASK_ROOT

# * Inject and auto-configure @sentry/serverless
# * https://docs.sentry.io/platforms/node/guides/aws-lambda/container-image/
COPY --from=public.ecr.aws/sentry/sentry-node-serverless-sdk:28 /opt/ /opt

ENV \
	NODE_ENV=production \
	SENTRY_DSN=$SENTRY_DSN \
	SENTRY_TRACES_SAMPLE_RATE=0.001

# * Add regex as a workaround to try to COPY files may may not exist.
# * https://stackoverflow.com/a/46801962
COPY package*.json ./
RUN [ -f package-lock.json ] && npm ci || echo "Skip, no package-lock.json file found"

# ! Must come after installing packages for some unknown reason
ENV NODE_OPTIONS="-r @sentry/serverless/dist/awslambda-auto"

COPY . .

# * Give AWS permission to access directories and run files.
# * https://repost.aws/knowledge-center/lambda-deployment-package-errors
RUN \
	find . -type d -exec chmod 755 {} \; && \
	find . -type f -exec chmod 644 {} \;

CMD [ "index.handler" ]
