# syntax=docker/dockerfile:1
FROM public.ecr.aws/lambda/nodejs:14

COPY --from=public.ecr.aws/sentry/sentry-node-serverless-sdk:28 /opt/ /opt

WORKDIR $LAMBDA_TASK_ROOT

COPY package*.json ./
RUN [ -f package-lock.json ] && npm ci || echo Skip

COPY . .

RUN find . -type d -exec chmod 755 {} \;
RUN find . -type f -exec chmod 644 {} \;

ENV \
        NODE_ENV=production \
        SENTRY_DSN=$SENTRY_DSN \
        SENTRY_TRACES_SAMPLE_RATE=0.001

CMD [ "index.handler" ]
